# Generated by Django 3.2 on 2024-04-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('otp', models.CharField(help_text='OTP code', max_length=50, verbose_name='OTP code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otp', serialize=False, to='users.user', verbose_name='User')),
                ('exp_time', models.DateTimeField(verbose_name='Expiration time')),
            ],
            options={
                'verbose_name': 'OTP code',
                'verbose_name_plural': 'Otp codes',
            },
        ),
    ]
